#!/usr/bin/env python3
import sys
import requests


from core.iGT import iGT

choice = 0

if sys.version_info < (3, 0):
    input = raw_input


def banner():
    print ('''
=================================

 ██╗███████╗██╗ ██████╗ ████████╗
███║╚════██║╚═╝██╔════╝ ╚══██╔══╝
╚██║    ██╔╝██║██║  ███╗   ██║   
 ██║   ██╔╝ ██║██║   ██║   ██║   
 ██║   ██║  ██║╚██████╔╝   ██║   
 ╚═╝   ╚═╝  ╚═╝ ╚═════╝    ╚═╝   
=================================''' )


def menu():
    print('''
1. Censys 
2. NS lookup
3. Port scan
4. Whois lookup
5. Detect honeypot
6. Reverse IP lookup
7. Detect web technologies
''' )


def iGTentry(choice):
    banner()
    while True:
        menu()
        result = False
        choice = input('~: ')
        iGT(choice)
        banner()


try:
    iGTentry(choice)
except KeyboardInterrupt:
        quit('')
